### ISSUE TITLE
Constructor without params

### ISSUE THREAD

**Issue by alexleandrom** [ranjan-rk/spring-social-flickr#2]
Hi I was looking to you spring-social lib and in FlickrTemplate has 2 constructors. 

One with parameters:
public FlickrTemplate(String consumerKey, String consumerSecret, String accessToken, String accessTokenSecret)

Second without parameters:
public FlickrTemplate()

I am trying to call the second, because I just call for Photos.Info,
http://www.flickr.com/services/api/flickr.photos.getInfo.html
so I dont need to pass the secret to call this, only the key.

Dont have in FlickrTemplate a constructor which I need to pass only the key.

**Comment by hemant24** [comment]
Hi alexleandrom,
Thanks for spending time to look into the library. The issue you have pointed is correct. Currently there seems no way to call public API. As you have mentioned, there should be a constructor which take key as parameter
and use this key to call public API. I will made changes to lib and let you know.

Thanks,
Hemant Sachdeva

**Comment by hemant24** [comment]
Hi alexleandrom,

I have made the changes to the FlickrTemplate to accept consumer key. Now you can call public API. Same is shown at https://github.com/ranjan-rk/spring-social-flickr/blob/master/core/src/test/java/org/springframework/social/flickr/connect/FlickStandaloneTest.java
